### ISSUE TITLE
Circular_end within critical area model applied two times

### ISSUE THREAD

**Issue by JanisMauch** [JARUS-QM/casex#3]
To my understanding the circular_end is supposed to be a buffer at the beginning and the end of the areas in the form of a half circle. Currently, the JARUS area model adds the circular_end area to the glide_area and the slide_area individually, as you can see in the code below. However, the shown area model within SORA 2.5 and its formula suggest that the circular_end should only be applied once instead of twice. Since the glide and slide areas are directly adjacent this would mean one circle too much gets added. I have illustrated this point in another graphic and made a suggestion on how to solve this issue within the critical_area_models.py file in line 238.

![image001](https://user-images.githubusercontent.com/91762756/216015967-e634ce49-9f38-4e68-b73b-9710996cd439.png)

```
            circular_end = math.pi * np.power(self.buffer + aircraft.width / 2, 2)
            glide_area = 2 * (self.buffer + aircraft.width / 2) * glide_distance + circular_end
            slide_area = slide_distance_lethal * (2 * self.buffer + aircraft.width) + circular_end

            # Concession for aircraft below 1 m.
            if aircraft.width <= 1:
                slide_distance_lethal = 0
                slide_area = 0
                LA_inert = glide_area     #Added another LA_inert assignment to make sure the circular end is not substracted for the <= 1 case
            else:
                LA_inert = glide_area + slide_area - circular_end     #Substract the circular_end if area consists of glide and slide
```

**Comment by AlaCourHarbo** [comment]
Yes, that seems to be a mistake of double counting. It will be fixed in the next update.
